apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapipke-deployment"
  namespace: coolapipke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "coolapipke"
  template:
    metadata:
      labels:
        app: "coolapipke"
    spec:
      containers:
        - name: "coolapipke"
          image: "acrpke.azurecr.io/coolapipke:1.0.0"
          ports:
          - containerPort: 3000
