apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapipke-deployment"
  namespace: coolapipke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "coolapipke"
  template:
    metadata:
      labels:
        app: "coolapipke"
    spec:
      containers:
        - name: "coolapipke"
          image: "acrpke.azurecr.io/coolapipke:1.0.0"
          ports:
          - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "0.2"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"