apiVersion: v1
kind: Service
metadata:
    name: "coolapipke-service"
    namespace: coolapipke
    labels:
        app: "coolapipke"
spec:
    #type: LoadBalancer
    externalIPs:
    - 20.103.169.33
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "coolapipke"
