apiVersion: v1
kind: Service
metadata:
    name: "coolapipke-service"
    namespace: coolapi
    labels:
        app: "coolapipke"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "coolapipke"
